"""Write the standard header cell of every notebook, from the README timetable.

Usage (from the repository root):

    python tools/build_headers.py                 # all notebooks
    python tools/build_headers.py path/to/nb.ipynb [more.ipynb ...]

For a notebook numbered NN the script looks up the timetable row of session NN
in README.md (day, time, room, session name, tutors) and writes a Markdown
header cell with the title, session details, a link to the matching exercise
and solution notebooks, and an "Open in Colab" badge. Exercise and solution
notebooks get the corresponding header (with a link back to the session).

If the notebook reads files from the data folder (its code mentions "data/"),
a "Colab only" code cell that downloads the material is inserted after the
header, so that the Colab badge actually leads to a working notebook.

The script is idempotent: a header or setup cell it wrote before is replaced,
an old hand-written header (the grey HTML box) is replaced as well, and any
introductory text that followed the old box in the same cell is kept.
"""

import os
import re
import sys
import glob
import datetime

import nbformat

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import (NOTEBOOK_DIRS, BLOB_URL, COLAB_URL, GITHUB_URL, BRANCH, YEAR,  # noqa: E402
                    TAG_SKIP)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER = "<!-- bootcamp-header: generated by tools/build_headers.py, edit the README timetable instead -->"
SETUP_TAG = "colab-setup"
BADGE = "https://colab.research.google.com/assets/colab-badge.svg"
DAYS = {"Mon": "Monday", "Tue": "Tuesday", "Wed": "Wednesday", "Thu": "Thursday", "Fri": "Friday"}


def read_timetable():
    """Return {NN: {day, time, room, name, tutors}} from the README tables."""
    sessions = {}
    row = re.compile(r"^\|\s*(\w{3}) (\d\d)/(\d\d)\s*\|\s*([\d:]*)\s*\|\s*([^|]*)\|\s*([^|]*)\|\s*([^|]*)\|")
    for line in open(os.path.join(ROOT, "README.md"), encoding="utf-8"):
        m = row.match(line)
        if not m:
            continue
        day, dd, mm, time, room, session, tutors = m.groups()
        num = re.search(r"`(\d\d)`", session)
        if not num:
            continue
        name = session.split(":`")[0] if ":`" in session else session.split(": `")[0]
        name = re.sub(r"[`*]", "", name).strip()
        date = datetime.date(YEAR, int(mm), int(dd))
        sessions[num.group(1)] = {
            "date": f"{DAYS[day]} {date.day} {date.strftime('%B')} {date.year}",
            "time": time.strip(), "room": room.strip(), "name": name, "tutors": tutors.strip(),
        }
    return sessions


def find(folder, num):
    hits = sorted(glob.glob(os.path.join(ROOT, folder, f"{num}_*.ipynb")))
    return os.path.relpath(hits[0], ROOT) if hits else None


def header_text(path, sessions):
    rel = os.path.relpath(path, ROOT)
    folder, base = os.path.split(rel)
    num = base[:2]
    s = sessions.get(num)
    if s is None:
        raise SystemExit(f"{rel}: no session `{num}` in the README timetable")
    session_nb = find("notebooks", num)
    ex_nb = find("exercises/questions", num)
    sol_nb = find("exercises/solutions", num)
    link = lambda p: f"[`{os.path.basename(p)}`]({BLOB_URL}/{p})"

    lines = [MARKER]
    if folder == "notebooks":
        lines += [f"# {s['name']}", ""]
        lines += [f"**Session:** {s['date']}, {s['time']}-{end_time(s['time'])}, room {s['room']}  "]
        lines += [f"**Tutors:** {s['tutors']}  "]
        if ex_nb:
            extra = f" (solutions: {link(sol_nb)})" if sol_nb else ""
            lines += [f"**Exercises:** {link(ex_nb)}{extra}  "]
        elif sol_nb:
            lines += [f"**Solution:** {link(sol_nb)} (look at it after the session, not before)  "]
    elif folder == "exercises/questions":
        lines += [f"# Exercises: {s['name']}", ""]
        lines += [f"These exercises go with the session {link(session_nb)} ({s['date']}).  "]
        if sol_nb:
            lines += [f"Solutions: {link(sol_nb)}  "]
    else:
        lines += [f"# Solutions: {s['name']}", ""]
        if ex_nb:
            lines += [f"Worked solutions to the exercises in {link(ex_nb)}, "
                      f"which go with the session {link(session_nb)}.  "]
        else:
            lines += [f"Worked solutions for the session {link(session_nb)}.  "]
    lines += ["", f"[![Open in Colab]({BADGE})]({COLAB_URL}/{rel})"]
    return "\n".join(lines)


def end_time(start):
    h, m = start.split(":")
    return f"{int(h) + 2}:{m}"


def setup_cell(path):
    folder = os.path.dirname(os.path.relpath(path, ROOT))
    src = (
        "# Run this cell only if you are working on Google Colab: it downloads the course\n"
        "# material (notebooks and data) so that the file paths in this notebook work.\n"
        "# On your own computer you can skip it.\n"
        f"!git clone --quiet --depth 1 --branch {BRANCH} {GITHUB_URL}.git bootcamp\n"
        f"%cd bootcamp/{folder}"
    )
    cell = nbformat.v4.new_code_cell(src)
    cell.metadata["tags"] = [SETUP_TAG, TAG_SKIP]
    return cell


def reads_data(nb):
    return any(c.cell_type == "code" and "data/" in "".join(c.source) for c in nb.cells)


def process(path, sessions):
    nb = nbformat.read(path, as_version=4)
    cells = nb.cells

    # Drop a setup cell we wrote before.
    cells[:] = [c for c in cells if SETUP_TAG not in c.get("metadata", {}).get("tags", [])]

    header = nbformat.v4.new_markdown_cell(header_text(path, sessions))
    first = cells[0] if cells else None
    if first is not None and first.cell_type == "markdown" and (
            MARKER in first.source or "**Staff:**" in first.source or "<div" in first.source[:20]):
        tail = ""
        if MARKER not in first.source and "</div>" in first.source:
            tail = first.source.rsplit("</div>", 1)[1].strip()
        cells[0] = header
        if tail:
            cells.insert(1, nbformat.v4.new_markdown_cell(tail))
    else:
        cells.insert(0, header)

    if reads_data(nb):
        cells.insert(1, setup_cell(path))

    nbformat.write(nb, path)
    return os.path.relpath(path, ROOT)


def main(argv):
    sessions = read_timetable()
    paths = argv or [p for d in NOTEBOOK_DIRS for p in sorted(glob.glob(os.path.join(ROOT, d, "*.ipynb")))]
    for p in paths:
        print("header written:", process(os.path.abspath(p), sessions))


if __name__ == "__main__":
    main(sys.argv[1:])
